### ISSUE TITLE
Type error when running the amortized inference

### ISSUE THREAD

**Issue by Chunpai** [mhw32/variational-item-response-theory-public#1]
This issue occurs when I run the code first time.

Traceback (most recent call last):
  File "src/torch_core/vi.py", line 364, in <module>
    train_logp = get_log_marginal_density(train_loader)
  File "src/torch_core/vi.py", line 199, in get_log_marginal_density
    marginal = model.log_marginal(
TypeError: log_marginal() got multiple values for argument 'num_samples'

It does not show up in my second run, and I am not sure why it happens.

**Comment by AlphaMoury** [comment]
Same here, is it a pytorch version problem perhaps?
